"""onay akisi

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 16:15:33.034729
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eposta', sa.String(length=254), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('parola_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('basarisiz_giris', sa.Integer(), server_default='0', nullable=False),
    sa.Column('kilit_bitis', sa.DateTime(), nullable=True),
    sa.Column('son_giris', sa.DateTime(), nullable=True),
    sa.Column('olusturuldu', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kullanicilar')),
    sa.UniqueConstraint('eposta', name=op.f('uq_kullanicilar_eposta'))
    )
    op.create_table('denetim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zaman', sa.DateTime(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('islem', sa.String(length=50), nullable=False),
    sa.Column('detay', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], name=op.f('fk_denetim_kullanici_id_kullanicilar')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_denetim'))
    )
    with op.batch_alter_table('kayitlar', schema=None) as batch_op:
        # Elle düzeltildi: autogenerate SQLite'a göre sa.text('0') üretiyor; PostgreSQL'de boolean
        # sütuna DEFAULT 0 hata verir. sa.false() her veritabanında doğru ifadeye çevrilir.
        batch_op.add_column(sa.Column('haric', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('raporlar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('durum', sa.String(length=20), server_default='GONDERILDI', nullable=False))
        batch_op.add_column(sa.Column('karar_veren_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('karar_zamani', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('karar_notu', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_raporlar_karar_veren_id_kullanicilar'), 'kullanicilar', ['karar_veren_id'], ['id'])

    # ### end Alembic commands ###

    # Veri düzeltmesi: onay akışından önce gönderilemeyen raporlar (gonderildi boş) "GONDERILDI"
    # görünmesin. O raporlara kayıt bağlanmamıştı; kayıtları zaten sonraki rapora kalmıştı.
    op.execute("UPDATE raporlar SET durum = 'IPTAL' WHERE gonderildi IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raporlar', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_raporlar_karar_veren_id_kullanicilar'), type_='foreignkey')
        batch_op.drop_column('karar_notu')
        batch_op.drop_column('karar_zamani')
        batch_op.drop_column('karar_veren_id')
        batch_op.drop_column('durum')

    with op.batch_alter_table('kayitlar', schema=None) as batch_op:
        batch_op.drop_column('haric')

    op.drop_table('denetim')
    op.drop_table('kullanicilar')
    # ### end Alembic commands ###
