"""gonderim denemesi

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 18:04:05.752182
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raporlar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gonderim_denemesi', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raporlar', schema=None) as batch_op:
        batch_op.drop_column('gonderim_denemesi')

    # ### end Alembic commands ###
