"""ilk sema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 15:19:39.443869
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calismalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslangic', sa.DateTime(), nullable=False),
    sa.Column('bitis', sa.DateTime(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('ozet', sa.JSON(), nullable=False),
    sa.Column('hata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calismalar'))
    )
    op.create_table('kaynak_durumu',
    sa.Column('kaynak', sa.String(length=50), nullable=False),
    sa.Column('checkpoint', sa.String(length=50), nullable=False),
    sa.Column('guncellendi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('kaynak', name=op.f('pk_kaynak_durumu'))
    )
    op.create_table('kayitlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kaynak', sa.String(length=50), nullable=False),
    sa.Column('dis_id', sa.String(length=500), nullable=False),
    sa.Column('yayin_tarihi', sa.Date(), nullable=False),
    sa.Column('baslik', sa.Text(), nullable=False),
    sa.Column('tur', sa.String(length=200), nullable=False),
    sa.Column('bolum', sa.String(length=200), nullable=False),
    sa.Column('sayi', sa.Integer(), nullable=True),
    sa.Column('mukerrer', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('kaynakca', sa.Text(), nullable=False),
    sa.Column('ilgili', sa.Boolean(), nullable=False),
    sa.Column('eslesmeler', sa.JSON(), nullable=False),
    sa.Column('is_kollari', sa.JSON(), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=True),
    sa.Column('icerik_durumu', sa.String(length=20), nullable=False),
    sa.Column('ilk_gorulme', sa.DateTime(), nullable=False),
    sa.Column('calisma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calisma_id'], ['calismalar.id'], name=op.f('fk_kayitlar_calisma_id_calismalar')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kayitlar')),
    sa.UniqueConstraint('kaynak', 'dis_id', name=op.f('uq_kayitlar_kaynak'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kayitlar')
    op.drop_table('kaynak_durumu')
    op.drop_table('calismalar')
    # ### end Alembic commands ###
