"""raporlar

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 15:55:08.051513
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raporlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olusturuldu', sa.DateTime(), nullable=False),
    sa.Column('gonderildi', sa.DateTime(), nullable=True),
    sa.Column('konu', sa.String(length=300), nullable=False),
    sa.Column('alicilar', sa.JSON(), nullable=False),
    sa.Column('kayit_sayisi', sa.Integer(), nullable=False),
    sa.Column('hata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raporlar'))
    )
    with op.batch_alter_table('kayitlar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rapor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_kayitlar_rapor_id_raporlar'), 'raporlar', ['rapor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kayitlar', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_kayitlar_rapor_id_raporlar'), type_='foreignkey')
        batch_op.drop_column('rapor_id')

    op.drop_table('raporlar')
    # ### end Alembic commands ###
