"""surum takibi

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-02 00:05:28.190463
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('izlenen_mevzuat',
    sa.Column('anahtar', sa.String(length=50), nullable=False),
    sa.Column('ad', sa.Text(), nullable=False),
    sa.Column('neden', sa.String(length=20), nullable=False),
    sa.Column('konu', sa.String(length=200), nullable=True),
    sa.Column('eklendi', sa.DateTime(), nullable=False),
    sa.Column('son_kontrol', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('anahtar', name=op.f('pk_izlenen_mevzuat'))
    )
    op.create_table('metin_surumleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anahtar', sa.String(length=50), nullable=False),
    sa.Column('cekildi', sa.DateTime(), nullable=False),
    sa.Column('ozet', sa.String(length=64), nullable=False),
    sa.Column('metin', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['anahtar'], ['izlenen_mevzuat.anahtar'], name=op.f('fk_metin_surumleri_anahtar_izlenen_mevzuat')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metin_surumleri'))
    )
    with op.batch_alter_table('metin_surumleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metin_surumleri_anahtar'), ['anahtar'], unique=False)

    with op.batch_alter_table('kayitlar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degisiklikler', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kayitlar', schema=None) as batch_op:
        batch_op.drop_column('degisiklikler')

    with op.batch_alter_table('metin_surumleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metin_surumleri_anahtar'))

    op.drop_table('metin_surumleri')
    op.drop_table('izlenen_mevzuat')
    # ### end Alembic commands ###
