"""alici gruplari

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-02 08:24:21.162063
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alici_gruplari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('is_kollari', sa.JSON(), nullable=False),
    sa.Column('adresler', sa.JSON(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('guncellendi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alici_gruplari')),
    sa.UniqueConstraint('ad', name=op.f('uq_alici_gruplari_ad'))
    )
    op.create_table('gonderimler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rapor_id', sa.Integer(), nullable=False),
    sa.Column('alicilar', sa.JSON(), nullable=False),
    sa.Column('kayit_idler', sa.JSON(), nullable=False),
    sa.Column('gruplar', sa.JSON(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('gonderim_denemesi', sa.DateTime(), nullable=True),
    sa.Column('gonderildi', sa.DateTime(), nullable=True),
    sa.Column('hata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rapor_id'], ['raporlar.id'], name=op.f('fk_gonderimler_rapor_id_raporlar')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gonderimler'))
    )
    with op.batch_alter_table('gonderimler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gonderimler_rapor_id'), ['rapor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gonderimler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gonderimler_rapor_id'))

    op.drop_table('gonderimler')
    op.drop_table('alici_gruplari')
    # ### end Alembic commands ###
