"""kaynak ve konu tanimlari

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-02 22:33:29.486739
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaynaklar',
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('etiket', sa.String(length=200), nullable=False),
    sa.Column('tip', sa.String(length=30), nullable=False),
    sa.Column('ayarlar', sa.JSON(), nullable=False),
    sa.Column('varsayilan_konular', sa.JSON(), nullable=False),
    sa.Column('sira', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('kaldirildi', sa.Boolean(), nullable=False),
    sa.Column('surum', sa.Integer(), nullable=False),
    sa.Column('guncelleme', sa.DateTime(), nullable=False),
    sa.Column('guncelleyen_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guncelleyen_id'], ['kullanicilar.id'], name=op.f('fk_kaynaklar_guncelleyen_id_kullanicilar')),
    sa.PrimaryKeyConstraint('ad', name=op.f('pk_kaynaklar'))
    )
    op.create_table('konular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('is_kollari', sa.JSON(), nullable=False),
    sa.Column('kelimeler', sa.JSON(), nullable=False),
    sa.Column('haric', sa.JSON(), nullable=False),
    sa.Column('dislanan', sa.JSON(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('surum', sa.Integer(), nullable=False),
    sa.Column('guncelleme', sa.DateTime(), nullable=False),
    sa.Column('guncelleyen_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guncelleyen_id'], ['kullanicilar.id'], name=op.f('fk_konular_guncelleyen_id_kullanicilar')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_konular')),
    sa.UniqueConstraint('ad', name=op.f('uq_konular_ad'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('konular')
    op.drop_table('kaynaklar')
    # ### end Alembic commands ###
